### ISSUE TITLE
Enable DNS Add On

### ISSUE THREAD

**Issue by errm** [rimusz/coreos-osx-gui-kubernetes-cluster#13]
It would be useful for the [DNS Add On](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns) to work out of the box, especially as some of the [examples](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples) depend on it.

I really like the project and think it is going to be a really useful tool in helping less ops inclined devs to know "Just Enough" about k8s to be dangerous.

I may well have a quick bash at getting this to work at some point over the weekend.

**Comment by rimusz** [comment]
@errm sure DNS Add on wold be nice to have there. I'm a bit busy with terraforming big k8s cluster setup.
If you have some spare time and can contribute, it would be awesome :) 

My small OS X coreos apps are big helpers for me to test things locally.
