### ISSUE TITLE
Kubernetes 1.0.3 breaks install because of "kube-system" namespace requirement

### ISSUE THREAD

**Issue by deftdawg** [rimusz/coreos-osx-gui-kubernetes-cluster#22]
My patch (#21) addresses a bit of the deployment side however I believe things are not deployed in a way that fleet expects, so the system is effectively broken. :(

**Comment by rimusz** [comment]
@jumpkick  I'm bit too busy to test the fix right, will do that in a few days.

**Comment by rimusz** [comment]
namespace gets created automatically by provisioning SkyDNS and Kube-UI, tested on k8s v1.0.6

```
 kubectl --namespace=kube-system get services NAME LABELS SELECTOR IP(S) PORT(S) kube-dns k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns k8s-app=kube-dns 10.100.0.10 53/UDP 53/TCP kube-ui k8s-app=kube-ui,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeUI k8s-app=kube-ui 10.100.244.210 80/TCP 
```

Latest release of App will not have an option to create that namespace, so I'm closing this one
