### ISSUE TITLE
Logging with Elasticsearch and Kibana

### ISSUE THREAD

**Issue by cloudmode** [rimusz/coreos-osx-gui-kubernetes-cluster#24]
First, this is awesome. No problems so far, it's proven to be exactly the test bed I needed to get up to speed on Kubernetes

I was trying to figure out how to add logging functionality (ElasticSearch and Kibana) referenced in http://kubernetes.io/v1.0/docs/getting-started-guides/logging-elasticsearch.html, but I'm having a hard time finding where the environment variables are set. 

Any suggestions on where I should start?

Thanks in advance.

**Comment by rimusz** [comment]
@cloudmode I have not used ElasticSearch and Kibana myself yet so I cannot give any suggestions, sorry.
