### ISSUE TITLE
additional flavors?

### ISSUE THREAD

**Issue by v1k0d3n** [rimusz/coreos-osx-gui-kubernetes-cluster#25]
ok, i'm in total agreement that this is an awesome project. great work! what are your thoughts about adding other OS flavors or networking options into the mix? it not a light undertaking, but it could be really useful for corps trying to look at rancher vs coreos vs fedora. i had an issue where i wanted to automate build-outs for dev off of my laptop (result: https://github.com/v1k0d3n/terraform-kubernetes), but I think having a wrapper around this approach, using the cockpit interface and the other kubernetes tools would be very powerful!

**Comment by rimusz** [comment]
@v1k0d3n  not sure I have time for other OS flavours, here at Deis we love using CoreOS :)
Somebody just can fork my repo and start from there

**Comment by v1k0d3n** [comment]
i know, and i'm personally a huge fan of CoreOS too. unfortunately, large organization split these roles into smaller groups so I'm not sure I'll have the final say. i just need to provide as much information as i possibly can, and hope that they come to some of the same conclusions. i understand about the workload and focus though...(i had to ask if it was a consideration though). :smile:

**Comment by rimusz** [comment]
@v1k0d3n I gave up with other OS flavours 18 months ago in favour of CoreOS, was running CoreOS in production in my previous work for long time :)

**Comment by v1k0d3n** [comment]
closing. may try to fork when i have some time. great project! you've made it drop dead simple for anyone to start exploring kubernetes!

**Comment by rimusz** [comment]
@v1k0d3n sure, I will ping you when I have time for refactoring :) any experience converting to swift ?
and btw thanks for the good words
