### ISSUE TITLE
support https api server

### ISSUE THREAD

**Issue by jchauncey** [rimusz/coreos-osx-gui-kubernetes-cluster#28]
I am trying to get these manifests working - https://github.com/pires/kubernetes-elasticsearch-cluster/issues/24

He pointed me in this direction - https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L149

And I started working on it but still couldnt seem to get it to work.

**Comment by pires** [comment]
@jchauncey are these the files we should change https://github.com/rimusz/coreos-osx-kubernetes-cluster/tree/master/src/fleet?

**Comment by jchauncey** [comment]
Yes

**Comment by tengfei86** [comment]
this problem still exist

**Comment by rimusz** [comment]
elasticsearch does not work, I have no idea why, but api supports https properly
opened an issue #32 for that problem

**Comment by pires** [comment]
Well, my Elasticsearch stuff works with:
- https://github.com/pires/kubernetes-vagrant-coreos-cluster
- Google Container Engine
- I also know of people using Tectonic that are running this, but haven't been updated there for a while.

This begs for more deep investigation but unfortunately, my time for this is very scarce.

**Comment by rimusz** [comment]
opened an issue #32 for that problem
