### ISSUE TITLE
Kubernetes API Server not starting

### ISSUE THREAD

**Issue by cryptolands** [rimusz/coreos-osx-gui-kubernetes-cluster#3]
Hey,
I installed everything and my Master and Minions are also running. But the kube-apiserver is not starting. 

when i do "journalctl -u kube-apiserver" on my Master, i get these errors:
Feb 18 11:24:24 k8smaster-01 systemd[1]: Starting Kubernetes API Server...
Feb 18 11:24:24 k8smaster-01 systemd[1]: kube-apiserver.service: control process exited, code=exited status=1
Feb 18 11:24:24 k8smaster-01 systemd[1]: Failed to start Kubernetes API Server.
Feb 18 11:24:24 k8smaster-01 systemd[1]: Unit kube-apiserver.service entered failed state.
Feb 18 11:24:24 k8smaster-01 systemd[1]: kube-apiserver.service failed.
Feb 18 11:24:24 k8smaster-01 chmod[2825]: /usr/bin/chmod: cannot access '/opt/bin/kube-apiserver': No such file or directory
Feb 18 11:24:34 k8smaster-01 systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.

What could be the problem?

**Comment by rimusz** [comment]
the error: k8smaster-01 chmod[2825]: /usr/bin/chmod: cannot access '/opt/bin/kube-apiserver': No such file or directory - tells that binary was not downloaded, try to restart the unit

**Comment by cryptolands** [comment]
Hey, i have restart all units with "Reload" but stillt the same error... :-(

**Comment by rimusz** [comment]
I will check the App and come back to you tomorrow

**Comment by rimusz** [comment]
I have made a new App v0.2.3, small changes in shell scripts and fleet units.
Please check it out.
Worked for me well to start the cluster from the scratch

**Comment by rimusz** [comment]
the latest release should fix this
