### ISSUE TITLE
elasticsearch-cluster does not work

### ISSUE THREAD

**Issue by rimusz** [rimusz/coreos-osx-gui-kubernetes-cluster#32]
pires/kubernetes-elasticsearch-cluster#24 still does not work even with api support for https

**Comment by pires** [comment]
@jchauncey this is a good time to test with the recently added HTTPS support and provide feedback.

**Comment by tengfei86** [comment]
I have tested ,thie problem  still exist

io.fabric8.kubernetes.api.KubernetesHelper] SSL handshake failed - this probably means that you need to trust the kubernetes root SSL certificate or set the environment variable KUBERNETES_TRUST_CERT
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:138)

**Comment by pires** [comment]
The certificate is not being provisioned to pods.

**Comment by pires** [comment]
Anyway, as a workaround, edit the replication-controllers and set env var `KUBERNETES_TRUST_CERT`

**Comment by tengfei86** [comment]
KUBERNETES_TRUST_CERT  aleady is true,but it does not work

**Comment by rimusz** [comment]
this one should be related to `runtime_config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true`

**Comment by rimusz** [comment]
v0.6.1 got `runtime_config=extensions/v1beta1=true,extensions/v1beta1/daemonsets=true` disabled

**Comment by gang99zheng** [comment]
Which certificate should be provisioned on Pod? Can we generate one and let Pod uses it by setting an env?
