### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by ghost** [rimusz/coreos-osx-gui-kubernetes-cluster#6]
For scheduling Yarn integrated with kubernetes makes sense i think.

Code: https://github.com/hortonworks/kubernetes-yarn
Intro: http://hortonworks.com/blog/docker-kubernetes-apache-hadoop-yarn/

How do you feel about this ? Wondering what your vision is and experience on this.

**Comment by rimusz** [comment]
nah, I'm not a big fan of complicated things.
https://mesosphere.com has similar stuff too.
Such things are (maybe) good if you want to run 10000+ servers and millions of containers :-)

But I will stick with simple CoreOS+Kubernetes setup, also http://kismatic.io with Google are working on the nice K8s UI https://www.youtube.com/watch?v=wQE-Rh6QtV0&feature=youtu.be

From my experience the simpler setup the less problems you get, currently I'm running dev/test/staging/production only on fleet units, all good, but systems grows so k8s becomes as a very good addition
